### ISSUE TITLE
Closed issue

### ISSUE THREAD

**Issue by MSTAT-Lseng** [xueziQQ/acer_e5_572_opencore_eif#1]
Closed issue

**Comment by xueziQQ** [comment]
Big Sur目前就是好看与iOS统一界面统一风格，但是底层问题太多，转向ARM架构为主后，X86的后期如何还不确定，许多APP报错，不适合生产环境。暂时没有尝试，打算再过1-2版本再升级。

**Comment by MSTAT-Lseng** [comment]
> Big Sur目前就是好看与iOS统一界面统一风格，但是底层问题太多，转向ARM架构为主后，X86的后期如何还不确定，许多APP报错，不适合生产环境。暂时没有尝试，打算再过1-2版本再升级。

谢谢
